routes/web.php
<?php
use \Illuminate\Support\Facades\Route;
use Illuminate\Routing\Router;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('program/search','ProgramController@search')
    ->name('program.search');
Route::get('program/{slug?}','ProgramController@index')
    ->name('program.list');

Route::resource('programs','ProgramController');

Route::get('addToFavourite','UserFlollowShowController@store')
    ->name('addToFavourite');

Route::get('likeDislikeEpisode','UserFavEpisodeController@likeDislikeEpisode')
    ->name('likeDislikeEpisode');

Route::get('noAuthView','Auth\LoginController@noAuthView')
    ->name('noAuthView');

Route::group([
//    'prefix'        => config('admin_new.route.prefix'),
//    'namespace'     => config('admin_new.route.namespace'),
    'middleware'    => ['auth'],
], function (Router $router) {
    $router->get('episode/{programEpisode}', 'ProgramEpisodeController@show')
        ->name('episode.show');
});

resources/views/home.blade.php
@extends('layouts.app')
@section('styles')
    <link href="{{asset('slider/ninja-slider.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('slider/thumbnail-slider.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('slickCarousel/slick.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('slickCarousel/slick-theme.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('slider/sliderCustom.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
    @include('mainSlider')
    <section>
    <div class="container margin-top-50">
        <div class="row " >
            <div class="col-sm-12">
                <p class="text-center title-text">
                    Series for you
                </p>
            </div>
        </div>
            <ul class="nav slick_show">
                @if(!empty($series))
                    @foreach($series as $program)
                        <li >
                            @include('programs.common.series')
                        </li>
                    @endforeach

                @endif
            </ul>
    </div>
        <div class="container margin-top-50">
        <div class="row " >
            <div class="col-sm-12">
                <p class="text-center title-text">
                    TV Shows for you
                </p>
            </div>
        </div>
            <ul class="nav slick_show">
                @if(!empty($TvShows))
                    @foreach($TvShows as $program)
                        <li >
                            @include('programs.common.tvShows')
                        </li>
                    @endforeach
                @endif
            </ul>
    </div>
    </section>
@endsection
@section('scripts')
    <script src="{{asset('slider/ninja-slider.js')}}"></script>

    <script src="{{asset('slider/thumbnail-slider.js')}}"
            ></script>
    <script src="{{asset('slickCarousel/slick.min.js')}}"  type="text/javascript" charset="utf-8"></script>
    <script src="{{asset('js/homePage.js')}}"></script>
@endsection

resources/views/mainSlider.blade.php
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12" style="padding: 0">
                <div class="slider_area">
                    <div id="ninja-slider" style="float:left;">
                        <div class="slider-inner">
                            <ul>
                                @if(!empty($TvShows))
                                    @foreach($TvShows->take(5) as $tvShow)
                                        <li>
                                            <a class="ns-img"
                                               href="{{asset('storage/'.$tvShow->main_image)}}">

                                                <div class="slider-text-container">
                                                    <div class="slider-text-content">
                                                        <p class="slider-text-title">
                                                            {{$tvShow->title}}
                                                        </p>
                                                        <p class="title-text">
                                                            {{arrangeProgramShowingDays($tvShow)}} {{date('H:i',strtotime($tvShow->broadcast_start_time))}}
                                                        </p>
                                                        <p>
                                                            <button
                                                                    data-link="{{route('programs.show',$tvShow->getUrlParams())}}}}"
                                                                    class="btn btn-rounded btn_watch_now go_to_link">
                                                                Watch now
                                                            </button>
                                                            @auth
                                                                <button
                                                                        data-link="{{route('addToFavourite',['program_id'=>$tvShow->id])}}"
                                                                        data-change="img.attr.src"
                                                                        class="btn btn-rounded btn_img_heart btn_change_inner_html">
                                                                    @if(!Auth::guest() &&  auth()->user()->checkFollowingProgram($tvShow->id))
                                                                        <img src="{{asset('images/Heart icon.png')}}" class="img-responsive heart_btn" />
                                                                    @else
                                                                        <img src="{{asset('images/heart copy 2.svg')}}" class="img-responsive heart_btn" />
                                                                    @endif
                                                                </button>
                                                            @else
                                                                <button
                                                                        data-link="{{route('noAuthView')}}"
                                                                        class="btn btn-rounded call-global-modal btn_img_heart">
                                                                    <img src="{{asset('images/heart copy 2.svg')}}" class="img-responsive heart_btn" />
                                                                </button>
                                                            @endauth
                                                        </p>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    @endforeach
                                @endif
                            </ul>
                        </div>
                    </div>
                    <div id="thumbnail-slider" style="float:left;">
                        <div class="inner">
                            <ul>
                                @if(!empty($TvShows))
                                    @foreach($TvShows->take(5) as $tvShow)
                                        <li>
                                            <a class="thumb"
                                               href="{{asset('storage/'.$tvShow->main_image)}}"></a>
                                        </li>
                                    @endforeach
                                @endif
                            </ul>
                        </div>
                    </div>
                    <div style="clear:both;"></div>
                </div>
            </div>
        </div>
    </div>
</section>